app/App.tsx, app/android/react-native-passport-reader/android/src/main/java/io/tradle/nfc/RNPassportReaderModule.kt, app/ios/PassportReader.swift, app/ios/Podfile, app/ios/Podfile.lock, app/src/screens/ProveScreen.tsx, common/src/utils/types.ts
- added face photo retrieval and display on android and ios
=> UI with photo

app/App.tsx, app/ios/MRZScannerModule.swift, app/ios/Podfile, app/ios/Podfile.lock, app/ios/ProofOfPassport.xcodeproj/project.pbxproj, app/ios/ProofOfPassport/Info.plist, app/package.json, app/yarn.lock, contracts/.gitignore
This branch update the following key areas:
- remove react-native-permissions dependencies
- add hint below iOS passport scanning
- update camera permission description for iOS
=> Remove react-native-permissions dependencies and add hint on ios scanning

app/src/screens/MainScreen.tsx, circuits/scripts/build_circuit.sh
- add text on Info page and extra randomness in circuit building script
=> Info texts

app/App.tsx, app/ios/Podfile.lock, app/package.json, app/src/utils/cameraScanner.ts, app/src/utils/nfcScanner.ts, app/src/utils/prover.ts, app/yarn.lock
- send zkey downloading success/failure and signature algorithm name so we find out why it works or doesn't for some people
- needed to debug the beta, might delete in prod
=> minimal analytics

app/README.md, app/ios/Podfile.lock, app/package.json, app/src/utils/zkeyDownload.ts, app/yarn.lock, common/src/constants/constants.ts
- uploading zipped versions of zkeys and unzipping them in the app
- ~2x size reduction
=> Zipping zkeys

app/README.md, app/android/app/src/main/java/com/awesomeproject/ProverModule.kt, app/scripts/build_android_module.sh, app/scripts/build_ios_module.sh, app/scripts/common.sh
fix build scripts and readme for new people, might still have an error when building from scratch during proving on android
=> Fix build scripts

app/package.json, app/src/screens/MainScreen.tsx, app/src/utils/contribute.ts, common/src/constants/constants.ts
This pull request enables users to securely submit their passport data by implementing AES-256-CBC encryption with dynamically generated keys and IVs.
Additionally, the AES key is encrypted with RSA-OAEP using the server's public key.
=> Contribute

app/src/apps/sbt.tsx, app/src/screens/MainScreen.tsx, app/src/screens/NextScreen.tsx, app/src/screens/ProveScreen.tsx, app/src/screens/RegisterScreen.tsx, app/src/stores/navigationStore.ts, app/src/stores/userStore.ts, app/src/utils/cameraScanner.ts, app/src/utils/nfcScanner.ts, app/src/utils/registration.ts, app/src/utils/zkeyDownload.ts, common/src/utils/generateInputs.ts
- Checking if commitment is registered before trying to register it
- Few improvements on the flow
- Nice screen if passport is currently not supported and suggestion to contribute
- Temporarily comment dg1HashOffset so that proof generation works
=> Few app fixes

circuits/circuits/tests/utils/rsapss_verifier.circom, circuits/scripts/build_utils_circuits.sh, circuits/tests/utils/rsapss_verifier.test.ts
Add rsapss-verifier to circuits
=> add rsa-pss-verifier

common/package.json, common/src/utils/csca.ts, common/src/utils/generateInputs.ts, common/src/utils/pubkeyTree.ts, common/src/utils/smtTree.ts, common/src/utils/utils.ts, common/yarn.lock
Reverts zk-passport/openpassport#228
error due to dependy of zk-kit-imt
"dependencies": {
"@zk-kit/utils": "1.2.1"
}
=> Revert "Update/openpassport zk kit"

app/android/app/build.gradle, app/android/react-native-passport-reader/android/src/main/java/io/tradle/nfc/RNPassportReaderModule.kt, app/ios/OpenPassport.xcodeproj/project.pbxproj, app/ios/Podfile.lock
=> Improve android reading

circuits/circuits/tests/utils/sha384_static_tester.circom, circuits/circuits/tests/utils/sha384_tester.circom, circuits/circuits/tests/utils/sha512_static_tester.circom, circuits/circuits/tests/utils/sha512_tester.circom, circuits/circuits/utils/sha2/sha384/sha384_hash_bits.circom, circuits/circuits/utils/sha2/sha512/sha512_hash_bits.circom, circuits/circuits/utils/shaBytes/dynamic/sha384Bytes.circom, circuits/circuits/utils/shaBytes/dynamic/sha512Bytes.circom, circuits/circuits/utils/shaBytes/shaBytesDynamic.circom, circuits/circuits/utils/shaBytes/shaBytesStatic.circom, circuits/circuits/utils/shaBytes/static/Sha384BytesStatic.circom, circuits/circuits/utils/shaBytes/static/Sha512BytesStatic.circom, circuits/tests/other_circuits/sha384.test.ts, circuits/tests/other_circuits/sha512.test.ts, common/src/utils/shaPad.ts
To Test,
``` bash
cd circuits 
yarn ts-mocha --max-old-space-size=8192 tests/other_circuits/sha512.test.ts
yarn ts-mocha --max-old-space-size=8192 tests/other_circuits/sha384.test.ts
```
=> Sha384 & sha512 circuits

circuits/circuits/dsc/dsc.circom, circuits/circuits/utils/passport/signatureVerifier.circom, circuits/tests/dsc/dsc.test.ts
=> hotfix off-by-one issues

contracts/scripts/findErrorSignature.ts
writing solidity error codes in comments
=> writing solidity error codes in comments

app/src/screens/Onboarding/LoadingScreen.tsx
- add a disclaimer on loading screen that loading takes time, so people don't drop.
This is a hotfix before https://github.com/selfxyz/self/issues/373
=> Add disclaimer on loading screen

app/src/utils/haptic.ts
=> increase feedback intensity on ios

app/src/screens/MockDataScreen.tsx, circuits/tests/dsc/test_cases.ts
fix destructuring error happening on mock passport screen
=> Fix mock flow

app/src/Navigation/dev.ts, app/src/Navigation/index.tsx, app/src/Navigation/settings.ts, app/src/screens/Settings/DevHapticFeedback.tsx, app/src/screens/Settings/DevSettingsScreen.tsx, app/src/utils/haptic.ts
- Update haptic library with unsuccessful, success and progress
- Also create new dev haptic feedback screen for Jon
new screen:
haptic notes:
=> SEL-178: Improve haptic feedback library

app/src/hooks/useConnectionModal.ts
do you think this would fix the internet connection issues you were seeing?
=> Improved internet connection check

app/ios/CameraView.swift, app/ios/LiveMRZScannerView.swift, app/ios/MRZScanner.swift, app/ios/PassportOCRViewManager.swift, app/src/components/native/PassportCamera.tsx, app/src/utils/utils.ts
1. Reads MRZ of ID cards
2. Returns 2 new fields.`documentType` and `countryCode`
- Success Animation before navigating to PassportNFCScanScreen
=> Read MRZ of ID cards - IOS - SEL-325

app/src/components/buttons/AbstractButton.tsx
address undefined is not an object issue
https://self-rfe.sentry.io/issues/6640908048/?project=4508860282503168&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0
=> [BUG] fix undefined tracking event error

app/android/app/build.gradle, app/android/react-native-passport-reader/android/build.gradle, app/src/screens/passport/NFCMethodSelectionScreen.tsx, app/src/types/react-native-passport-reader.d.ts, app/src/utils/nfcScanner.ts
- bumped android to build to `70`
- Updated JMRTD version
- Added CAN authentication support in android
=> CAN auth - android

app/android/react-native-passport-reader/android/src/main/java/io/tradle/nfc/APDULogger.kt, app/android/react-native-passport-reader/android/src/main/java/io/tradle/nfc/RNPassportReaderModule.kt
logs APDU command and responses to grafana
=> feat: log apdu
